spring:
  application:
    name: spring-cloud-eureka
server:
  port: 8002 # tomcat 端口 server1
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8001/eureka/,http://peer3:8003/eureka/
    #register-with-eureka: false # 表示是否注册本身到 eureka服务器
    #fetch-registry: false # 是否从eureka上获取注册信息